name: GitHub Actions Demo
on:
  push:
    branches:
      - main
    paths:
      - templates/**
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Install postmark client
        run: npm i postmark-cli -g
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            echo "Do something with this ${changed_file}."
          done
