name: GitHub Actions Demo
on:
  push:
    branches:
      - main
    paths:
      - templates/**
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Install postmark client
        run: npm i postmark-cli -g
      - name: Push common layouts
        working-directory: ./templates
        env:
          first_server_api_token: ${{secrets.FIRST_SERVER_API_TOKEN}}
        run: |
          echo "Pushing layouts..."
          cd ./_layouts
          echo "$first_server_api_token" | postmark templates push ./ -f
      - name: Push First server
        working-directory: ./templates
        env:
          first_server_api_token: ${{secrets.FIRST_SERVER_API_TOKEN}}
        run: |
          if [ -d "./first-server/_layouts" ] 
          then
            echo "Pushing layouts..."
            cd ./first-server/_layouts
            echo "$first_server_api_token" | postmark templates push ./ -f
          fi
          echo "Pushing templates..."
          cd ..
          echo "$first_server_api_token" | postmark templates push ./ -f
      - name: Push Second server
        working-directory: ./templates
        env:
          second_server_api_token: ${{secrets.SECOND_SERVER_API_TOKEN}}
        run: |
          if [ -d "./second-server/_layouts" ] 
          then
            echo "Pushing layouts..."
            cd ./second-server/_layouts
            echo "$second_server_api_token" | postmark templates push ./ -f
          fi
          echo "Pushing templates..."
          cd ..
          echo "$second_server_api_token" | postmark templates push ./ -f
        
          
