name: GitHub Actions Demo
on:
  push:
    branches:
      - main
    paths:
      - templates/**
defaults:
  run:
    working-directory: templates
env:
  first_server_api_token: ${{secrets.FIRST_SERVER_API_TOKEN}}
  second_server_api_token: ${{secrets.SECOND_SERVER_API_TOKEN}}
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          cache: 'npm'
          cache-dependency-path: 'templates/package-lock.json'
      - name: Install postmark client
        run: npm i postmark-cli
      - name: Push common layouts
        run: |
          echo "Pushing layouts..."
          cd ./_layouts
          echo "$first_server_api_token" | npx postmark templates push ./ -f
      - name: Push servers layouts
        run: |
          api_tokens=($first_server_api_token $second_server_api_token)
          server_routes=("first-server" "second-server")
          for i in ${!server_routes[@]}; do
            if [ -d "./${server_routes[$i]}/_layouts" ] 
            then
              echo "Pushing layouts for ${server_routes[$i]} ..."
              cd ./${server_routes[$i]}/_layouts
              echo "${api_tokens[$i]}" | npx postmark templates push ./ -f
              cd ../..
            else
              echo "No layouts to push from ${server_routes[$i]}"
            fi
          done
      - name: Push servers templates
        run: |
          api_tokens=($first_server_api_token $second_server_api_token)
          server_routes=("first-server" "second-server")
          for i in ${!server_routes[@]}; do
            echo "Pushing templates for ${server_routes[$i]} ..."
            cd ./${server_routes[$i]}/
            echo "${api_tokens[$i]}" | npx postmark templates push ./ -f
            cd ..
          done
