name: GitHub Actions Demo
on:
  push:
    branches:
      - main
    paths:
      - templates/**
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Install postmark client
        run: npm i postmark-cli -g
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          changed_directories=()
          for changed_file in ${{ steps.files.outputs.all }}; do
            case "$changed_file" in 
              *"templates"* ) changed_directories+="$(cut -d'/' -f2 <<<"$changed_file")" ;;
            esac
          done
          echo '::set-output name=CHANGED_DIRECTORIES::$changed_directories'
      - run: |
          echo "${{ steps.files.outputs.CHANGED_DIRECTORIES }}"
